name = "QuantizedArrays"
uuid = "a7db621c-8ce0-11e9-16a1-0f86dc86bd10"
authors = ["Corneliu Cofaru <cornel@oxoaresearch.com>"]
version = "0.1.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
